Update frontend to flask v3
So that the flask versions match between pre-award-frontend and
pre-award-stores.

We also update Flask-Babel, because v2 is not compatible with Flask v3

ImportError while loading conftest
'/Users/sam/git/runner/apps/funding-service-pre-award-frontend/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from app import create_app
app.py:6: in <module>
    from flask_babel import Babel, gettext, pgettext
.venv/lib/python3.10/site-packages/flask_babel/__init__.py:17: in
<module>
    from flask.helpers import locked_cached_property
E   ImportError: cannot import name 'locked_cached_property' from
'flask.helpers'
(/Users/sam/git/runner/apps/funding-service-pre-award-frontend/.venv/lib/python3.10/site-packages/flask/helpers.py)