Re-compile uv lock with pyscss
The previous lock file added `enum34`, which is actually only needed for
python <3.4.

I'm not sure why this got pulled it - it shouldn't be there. And it
broke our deploys, because it overwrites the stdlib `enum` package, which
then breaks other stdlib packages.

Traceback (most recent call last):
  File "/layers/paketo-buildpacks_pip-install/packages/bin/gunicorn",
line 3, in <module>
    import re
  File "/layers/paketo-buildpacks_cpython/cpython/lib/python3.10/re.py",
line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

To fix this I just did:

uv remove pyscss
uv add 'pyscss>=1.4.0'